#!/usr/bin/env python

#########################
#
# the script turns a fan on and off when temperature acquired by an external ADC MCP3008 
# exceeds thresholds.
#
# the script was tested on a raspberry pi running kodi on osmc using a 3.3v GPIO
#
#########################

#########################
#
# run-fan requires an NPN transistor and a resistor to be connected
# as follows:
# - emitter: connects to Raspberry GND and power supply GND
# - base: connects to 110 Ohm Resistor. The other pin of resistor to GPIO pin 25
# - collector: connects to fan GND
# - fan red (+): connects to external 12V power supply
#
# GPIO pin 25 is used, but it can be changed
#
#########################

#########################
#
# The original script is from:
# Source: https://github.com/dumbo25/rpi-fan/blob/master/run-fan.py
#
#########################

#########################
import Adafruit_GPIO.SPI as SPI
import Adafruit_MCP3008
import os
import time
import signal
import sys
import RPi.GPIO as GPIO
import datetime
import math
#########################
sleepTime = 30   # Time to sleep between checking the temperature
                # want to write unbuffered to file
fileLog = open('/var/log/run-fan.log', 'w+', 0)

#########################
SPI_PORT   = 0
SPI_DEVICE = 0
mcp = Adafruit_MCP3008.MCP3008(spi=SPI.SpiDev(SPI_PORT, SPI_DEVICE))

# Log messages should be time stamped
def timeStamp():
    t = time.time()
    s = datetime.datetime.fromtimestamp(t).strftime('%Y/%m/%d %H:%M:%S - ')
    return s

# Write messages in a standard format
def printMsg(s):
    fileLog.write(timeStamp() + s + "\n")

#########################
class Pin(object):
    pin = 25        # GPIO or BCM pin number to turn fan on and off

    def __init__(self):
        try:
            GPIO.setmode(GPIO.BCM)
            GPIO.setup(self.pin, GPIO.OUT)
            GPIO.setwarnings(False)
            printMsg("Initialized: run-fan using GPIO pin: " + str(self.pin))
        except:
            printMsg("If method setup doesn't work, need to run script as sudo")
            exit

    # resets all GPIO ports used by this program
    def exitPin(self):
        GPIO.cleanup()

    def set(self, state):
        GPIO.output(self.pin, state)

# Fan class
class Fan(object):
    fanOff = True

    def __init__(self):
        self.fanOff = True

    # Turn the fan on or off
    def setFan(self, temp, on, myPin):
        if on:
            printMsg("Turning fan on " + str(temp))
            myPin.set(on)
            self.fanOff = not on
        else:
            printMsg("Turning fan off " + str(temp))
            myPin.set(off)
            self.fanOff = on

# Temperature class
class Temperature(object):
    Temperature = 0.0
    startTemperature = 0.0
    stopTemperature = 0.0

    def __init__(self):

        # Start temperature in Celsius
        self.startTemperature = 40.0

        # Wait until the temperature is M degrees under the Max before shutting off
        self.stopTemperature = self.startTemperature - 5.0

        printMsg("Start fan at: " + str(self.startTemperature))
        printMsg("Stop fan at: " + str(self.stopTemperature))

    def getTemperature(self):
        temp=mcp.read_adc(1)
# Steinhart-Hart formula for NTC conversion. Beta=3950, NTC value=10K, pull-up resistor= 
        temp_conv=1.00/(((1/3950.00)*math.log(12000.00/(1024.00/temp-1)/10000.00))+(1/298.15))-273.15+6
        self.Temperature=temp_conv
        printMsg("Current Temperature:" +str(temp_conv))
# Using the acquired temperature, turn the fan on or off
    def checkTemperature(self, myFan, myPin):
        self.getTemperature()
        if self.Temperature > self.startTemperature:
            # need to turn fan on, but only if the fan is off
            if myFan.fanOff:
                myFan.setFan(self.Temperature, True, myPin)
        elif self.Temperature <= self.stopTemperature:
            # need to turn fan off, but only if the fan is on
            if not myFan.fanOff:
                myFan.setFan(self.Temperature, False, myPin)

printMsg("Starting thermostat")
try:
    myPin = Pin()
    myFan = Fan()
    myTemp = Temperature()
    while True:
        myTemp.checkTemperature(myFan, myPin)
        # Read the temperature every N sec (sleepTime)
        # Turning a device on & off can wear it out
        time.sleep(sleepTime)

except KeyboardInterrupt: # trap a CTRL+C keyboard interrupt
    printMsg("keyboard exception occurred")
    myPin.exitPin()
    fileLog.close()

except:
    printMsg("ERROR: an unhandled exception occurred")
    myPin.exitPin()
    fileLog.close()
